export type SliderKey='bustFullness'|'waistDefinition'|'hipWidth'|'gluteRoundness'|'gluteProjection'|'thighFullness'|'legProportion'|'visualImpact'
export interface BuilderStateV3{schemaVersion:3;dataVersion:'0.2.1';persona:{regionStyle:string;ageBand:string;archetype:string;vibes:string[]};face:{faceShape:string;featureVibe:string;hairstyle:string;makeup:string;expression:string};body:{frame:string;bustFullness:number;waistDefinition:number;hipWidth:number;gluteRoundness:number;gluteProjection:number;thighFullness:number;legProportion:number;visualImpact:number};outfit:{type:string;color:string;style:string;fit:string;accessories:string[]};pose:{mode:string;poseId:string;headDirection:string;handPosition:string;legPosition:string};scene:{location:string;time:string;atmosphere:string};camera:{framing:string;height:string;subjectView:string;photographyType:string;lensStyle:string};lighting:{lightType:string;visualStyle:string;rimLight:string;colorTone:string};systemLocks:{clearlyAdult:true;fictionalCharacter:true;nonExplicit:true;anatomyGuard:true}}
export type BuilderSection=keyof Omit<BuilderStateV3,'schemaVersion'|'dataVersion'|'systemLocks'>
export interface V2Option{id:string;labelZh:string;labelEn:string;prompt:{zh:string;en:string}}
export interface SliderDefinition{key:SliderKey;labelZh:string;labelEn:string;description:string}
export interface CharacterPreset{id:string;name:string;eyebrow:string;description:string;state:BuilderStateV3}
export interface ValidationResult{isValid:boolean;messages:string[]}
export interface PoseDefinition{id:string;mode:string;labelZh:string;labelEn:string;prompt:{zh:string;en:string};impliedValues:Record<string,string>;lockedFields:string[];allowedValues:Record<string,string[]>;explanation:string}
export interface FieldLock{field:string;value:string;sourceId:string;reason:string} export interface DisabledOption{optionId:string;field:string;reason:string} export interface CompatibilityChange{field:string;previousValue:unknown;nextValue:unknown;reason:string}
export interface CompatibilityResolution{nextState:BuilderStateV3;changes:CompatibilityChange[];lockedFields:FieldLock[];disabledOptions:DisabledOption[];messages:string[];requiresConfirmation:boolean}
