import{getPose,poseDefinitions}from'../data/poseDefinitions';import type{BuilderStateV3,CompatibilityChange,CompatibilityResolution,DisabledOption,FieldLock}from'../types/builderV3'
const get=(s:BuilderStateV3,path:string)=>path.split('.').reduce((v:any,k)=>v?.[k],s as any);const set=(s:BuilderStateV3,path:string,value:string)=>{const ks=path.split('.');let v:any=s;for(const k of ks.slice(0,-1))v=v[k];v[ks.at(-1)!]=value}
export function resolveDependencies(state:BuilderStateV3):CompatibilityResolution{const next=structuredClone(state),pose=getPose(next.pose.poseId)??getPose('pose-neutral')!,changes:CompatibilityChange[]=[];next.pose.mode=pose.mode;for(const[field,value]of Object.entries(pose.impliedValues)){const prev=get(next,field);if(prev!==value){set(next,field,value);changes.push({field,previousValue:prev,nextValue:value,reason:pose.explanation})}}const lockedFields:FieldLock[]=pose.lockedFields.map(field=>({field,value:get(next,field),sourceId:pose.id,reason:pose.explanation}));const disabledOptions:DisabledOption[]=[];for(const[field,allowed]of Object.entries(pose.allowedValues)){const current=get(next,field);if(!allowed.includes(current)){set(next,field,allowed[0]);changes.push({field,previousValue:current,nextValue:allowed[0],reason:pose.explanation})}for(const option of allByField[field]??[])if(!allowed.includes(option))disabledOptions.push({optionId:option,field,reason:`${pose.labelZh}僅支援相容的動作結構與鏡位。`})}if(pose.id==='pose-warrior')disabledOptions.push({optionId:'hands-ground',field:'pose.handPosition',reason:'戰士式需要向上或瑜珈延伸手勢。'});if(pose.mode==='standing')for(const id of['hands-ground'])disabledOptions.push({optionId:id,field:'pose.handPosition',reason:'一般站姿不可使用地面支撐。'});return{nextState:next,changes,lockedFields,disabledOptions,messages:changes.length?[`已套用${pose.labelZh}相容設定。`]:[],requiresConfirmation:changes.length>=3}}
const allByField:Record<string,string[]>={'camera.subjectView':['view-front','view-side','view-three-front','view-three-side','view-back'],'camera.framing':['frame-full','frame-thigh','frame-half','frame-portrait'],'camera.height':['cam-eye','cam-low','cam-high']}
export const applySelection=(state:BuilderStateV3,field:string,value:string)=>{const next=structuredClone(state);set(next,field,value);const result=resolveDependencies(next);if(field==='pose.poseId'&&['pose-cat-cow','pose-down-dog','pose-bridge'].includes(value))result.requiresConfirmation=true;if((field==='pose.headDirection'&&value==='head-look-back')||(field==='camera.subjectView'&&['view-back','view-three-side'].includes(value)&&result.nextState.pose.headDirection==='head-look-back'))result.messages.push('自然回望請保持柔和幅度，避免頸部與脊椎過度扭轉。');return result}
export const getDisabledReason=(r:CompatibilityResolution,field:string,id:string)=>r.disabledOptions.find(x=>x.field===field&&x.optionId===id)?.reason
export const getFieldLock=(r:CompatibilityResolution,field:string)=>r.lockedFields.find(x=>x.field===field)
export const getAvailableOptions=(r:CompatibilityResolution,field:string,ids:string[])=>ids.filter(id=>!getDisabledReason(r,field,id))
export const validateResolvedState=(r:CompatibilityResolution)=>{const p=getPose(r.nextState.pose.poseId);const errors:string[]=[];if(!p||p.mode!==r.nextState.pose.mode)errors.push('姿勢模式不一致');for(const f of r.lockedFields)if(get(r.nextState,f.field)!==f.value)errors.push(`${f.field} 鎖定值錯誤`);for(const[f,a]of Object.entries(p?.allowedValues??{}))if(!a.includes(get(r.nextState,f)))errors.push(`${f} 不相容`);if(Object.values(r.nextState.systemLocks).some(x=>x!==true))errors.push('安全鎖異常');return{isValid:!errors.length,messages:errors}}
export const validateFinalPrompt=(text:string)=>{const pairs=[['standing naturally','cat-cow'],['standing naturally','downward-facing dog'],['hands resting naturally','supporting the ground'],['front-view','back-look'],['portrait','downward-facing dog'],['crossed legs','kneeling']];const errors=pairs.filter(([a,b])=>text.includes(a)&&text.includes(b)).map(x=>x.join(' + '));return{isValid:!errors.length,messages:errors}}
export const createChangePreview=(r:CompatibilityResolution)=>r.changes.map(c=>`${c.field}：${String(c.nextValue)}`)
export{resolveDependencies as applyImpliedValues,resolveDependencies as removeInvalidSelections,resolveDependencies as applyLockedValues}
