import{findOption}from'../data/builderOptions';import{findCompositionOption}from'../data/compositionOptions';import{negativePromptTerms}from'../data/negativePrompt';import{getPose}from'../data/poseDefinitions';import type{BuilderStateV3,CharacterPreset,SliderKey,ValidationResult}from'../types/builderV3';import{validateFinalPrompt}from'./compatibilityEngine'
const find=(id:string)=>(findOption(id)??findCompositionOption(id))?.prompt.en??'',u=(a:string[])=>[...new Set(a.filter(Boolean))],band=(v:number)=>v<=20?0:v<=40?1:v<=60?2:v<=80?3:4
const phrases:Record<Exclude<SliderKey,'visualImpact'>,string[]>={bustFullness:['subtle upper-body silhouette','natural upper-body silhouette','softly fuller upper-body silhouette','prominently full yet balanced upper-body silhouette','dramatically full yet anatomically coherent upper-body silhouette'],waistDefinition:['natural waistline','understated waistline','gently defined waistline','strongly defined coherent waistline','dramatically defined coherent waistline'],hipWidth:['slender hip structure','natural hip width','softly fuller hip structure','prominent balanced hip structure','dramatic coherent hip structure'],gluteRoundness:['subtle hip contours','natural hip contours','softly rounded hip contours','prominently rounded balanced contours','dramatically rounded coherent contours'],gluteProjection:['subtle side contour','natural side contour','softly dimensional contour','prominent balanced contour','dramatic coherent projection'],thighFullness:['slender thigh contours','natural thigh proportions','softly fuller thighs','prominently full balanced thighs','dramatically full coherent thighs'],legProportion:['compact balanced legs','balanced leg ratio','softly elongated legs','prominently elongated plausible legs','dramatic model-like coherent legs']}
export const getSliderSemantic=(k:SliderKey,v:number)=>({en:['Subtle','Natural','Defined','Prominent','Dramatic'][band(v)],zh:['細緻收斂','自然低調','柔和明確','鮮明平衡','戲劇但合理'][band(v)],description:k==='visualImpact'?'只調整構圖與視覺語氣。':k})
export const mapSliderToPromptFragment=(k:SliderKey,v:number,mode:'natural'|'impact'='natural')=>k==='visualImpact'?(mode==='impact'?['clean composition','defined silhouette','strong editorial composition','sculpted visual contour','dramatic editorial presence'][band(v)]:['lifestyle restraint','natural silhouette','editorial polish','controlled visual tension','refined dramatic editorial'][band(v)]):phrases[k][band(v)]
const bodyKeys:Exclude<SliderKey,'visualImpact'>[]=['bustFullness','waistDefinition','hipWidth','gluteRoundness','gluteProjection','thighFullness','legProportion']
export const buildPosePrompt=(s:BuilderStateV3)=>getPose(s.pose.poseId)?.prompt.en??'a coherent neutral pose';export const buildSupportStructurePrompt=(s:BuilderStateV3)=>u([find(s.pose.handPosition),find(s.pose.legPosition)]).join(', ');export const buildSubjectViewPrompt=(s:BuilderStateV3)=>find(s.camera.subjectView)
const core=(s:BuilderStateV3)=>['a completely fictional, clearly adult woman',find(s.persona.regionStyle),find(s.persona.ageBand),find(s.persona.archetype),...s.persona.vibes.map(find),find(s.face.faceShape),find(s.face.featureVibe),find(s.face.hairstyle),find(s.face.makeup),find(s.face.expression),find(s.body.frame),...bodyKeys.map(k=>mapSliderToPromptFragment(k,s.body[k])),find(s.outfit.type),find(s.outfit.color),find(s.outfit.style),find(s.outfit.fit),buildPosePrompt(s),buildSupportStructurePrompt(s),find(s.pose.headDirection),buildSubjectViewPrompt(s),find(s.camera.framing),find(s.camera.height),find(s.scene.location),find(s.scene.time),find(s.scene.atmosphere),find(s.lighting.lightType),find(s.lighting.rimLight),find(s.lighting.visualStyle)]
const end=['mature adult presence','tasteful non-explicit photography','anatomically coherent proportions','realistic anatomy','original fictional identity','no resemblance to any real person']
export const buildNaturalPrompt=(s:BuilderStateV3)=>u([...core(s),mapSliderToPromptFragment('visualImpact',s.body.visualImpact),...end]).join(', ');export const buildHighImpactPrompt=(s:BuilderStateV3)=>u([...core(s),mapSliderToPromptFragment('visualImpact',s.body.visualImpact,'impact'),'controlled pose tension',...end]).join(', ')
export const buildCharacterSummary=(s:BuilderStateV3)=>u([findOption(s.persona.archetype)?.labelZh??'虛構成年女性',findOption(s.persona.ageBand)?.labelZh??'明確成年',getPose(s.pose.poseId)?.labelZh??'自訂姿態',findCompositionOption(s.camera.subjectView)?.labelZh??'',findCompositionOption(s.camera.framing)?.labelZh??'',`視覺衝擊 ${s.body.visualImpact}`]).join('\n');export const buildNegativePrompt=()=>u([...negativePromptTerms,'real person likeness','celebrity likeness','fetishized body-part close-up']).join(', ');export const buildAllPrompts=(s:BuilderStateV3)=>`角色摘要\n────\n${buildCharacterSummary(s)}\n\nNatural Portrait Prompt\n────\n${buildNaturalPrompt(s)}\n\nHigh-Impact Editorial Prompt\n────\n${buildHighImpactPrompt(s)}\n\nNegative Prompt\n────\n${buildNegativePrompt()}`
export const validateBuilderState=(s:BuilderStateV3):ValidationResult=>({isValid:s.schemaVersion===3&&s.dataVersion==='0.2.1'&&Object.values(s.systemLocks).every(Boolean),messages:[]});export const validateResolvedPrompt=(s:BuilderStateV3)=>validateFinalPrompt(buildNaturalPrompt(s));export const applyCharacterPreset=(p:CharacterPreset)=>structuredClone(p.state)
