import{findOption}from'../data/builderOptions';import{findCompositionOption}from'../data/compositionOptions';import{negativePromptTerms}from'../data/negativePrompt';import{getPose}from'../data/poseDefinitions';import type{BuilderStateV3,CharacterPreset,SliderKey,ValidationResult}from'../types/builderV3';import{validateFinalPrompt}from'./compatibilityEngine'
const find=(id:string)=>(findOption(id)??findCompositionOption(id))?.prompt.en??'',unique=(items:string[])=>[...new Set(items.map(x=>x.trim()).filter(Boolean))],band=(v:number)=>v<=20?0:v<=40?1:v<=60?2:v<=80?3:4
type BodyKey=Exclude<SliderKey,'visualImpact'>;const bodyKeys:BodyKey[]=['bustFullness','waistDefinition','hipWidth','gluteRoundness','gluteProjection','thighFullness','legProportion']
const labels:Record<BodyKey,string>={bustFullness:'上半身豐滿度',waistDefinition:'腰線',hipWidth:'胯部寬度',gluteRoundness:'下半身圓潤度',gluteProjection:'側面立體度',thighFullness:'大腿豐盈度',legProportion:'腿身比例'}
const phrases:Record<BodyKey,string[]>={
bustFullness:['a subtle upper-body silhouette','a naturally balanced upper-body silhouette','a softly fuller upper-body silhouette','a prominently full yet balanced upper-body silhouette','a very full, visually prominent yet proportionally balanced upper-body silhouette'],
waistDefinition:['a softly natural waistline','a natural understated waistline','a clearly defined waistline','a strongly defined yet coherent waistline','an exceptionally defined yet anatomically coherent waistline'],
hipWidth:['a slender balanced hip structure','a natural hip structure','a softly fuller hip structure','a prominently broader yet balanced hip structure','a distinctly broad, curvaceous yet anatomically balanced hip structure'],
gluteRoundness:['subtle lower-body contours','natural rounded lower-body contours','softly rounded lower-body contours','prominently rounded yet balanced lower-body contours','strongly rounded, visually pronounced yet anatomically coherent lower-body contours'],
gluteProjection:['a subtle side-profile contour','a natural side-profile contour','a softly dimensional side-profile contour','a pronounced yet balanced side-profile contour','a highly dimensional yet anatomically coherent side-profile contour'],
thighFullness:['slender yet healthy thigh contours','natural thigh proportions','softly fuller thigh contours','prominently full yet balanced thigh contours','very full yet proportionally balanced thigh contours'],
legProportion:['naturally compact leg proportions','balanced leg-to-body proportions','softly elongated leg lines','prominently elongated yet plausible leg lines','strongly elongated, model-like yet anatomically plausible leg proportions']}
export const getSliderSemantic=(key:SliderKey,value:number)=>({en:['Subtle','Natural','Defined','Prominent','Very high'][band(value)],zh:['細緻收斂','自然低調','柔和明確','鮮明平衡','高值但合理'][band(value)],description:key==='visualImpact'?'只調整構圖、剪影、光線與 Editorial 語氣。':key})
export const mapSliderToPromptFragment=(key:SliderKey,value:number,mode:'natural'|'impact'='natural')=>key==='visualImpact'?(mode==='impact'?['clean lifestyle composition','defined natural silhouette','strong fashion-editorial composition','sculpted visual contour, controlled pose tension and defined rim lighting','dramatic editorial presence, powerful composition, sculpted whole-figure silhouette and controlled rim-lit visual tension'][band(value)]:['natural lifestyle restraint','subtle silhouette emphasis','polished editorial presence','strong but controlled silhouette emphasis','refined high-impact editorial presence with powerful yet coherent visual framing'][band(value)]):phrases[key][band(value)]
export function rankBodyFeatures(state:BuilderStateV3){const ground=['pose-cat-cow','pose-down-dog','pose-bridge','pose-seated-fold'].includes(state.pose.poseId);return bodyKeys.map(key=>({key,value:state.body[key]})).sort((a,b)=>(b.value-(ground&&b.key==='legProportion'?35:0))-(a.value-(ground&&a.key==='legProportion'?35:0)))}
export function selectDominantBodyFeatures(state:BuilderStateV3,limit:number){const grouped=rankBodyFeatures(state).filter(x=>x.key!=='gluteProjection');const lower=grouped.find(x=>x.key==='gluteRoundness');if(lower)lower.value=Math.max(state.body.gluteRoundness,state.body.gluteProjection);return grouped.sort((a,b)=>b.value-a.value).slice(0,limit)}
export function mergeRelatedBodyFeatures(features:{key:BodyKey;value:number}[]){return features}
export function buildHolisticBodyDescriptor(state:BuilderStateV3){const values=bodyKeys.map(k=>state.body[k]),compressed=values.filter(v=>v>=81).length>=3||values.filter(v=>v>=61).length>=5;return compressed?'a visually powerful, highly curvaceous body frame with strong but balanced proportions':'a coherent body silhouette with balanced waist-to-hip transition and natural overall proportions'}
const featurePhrase=(f:{key:BodyKey;value:number},state:BuilderStateV3)=>f.key==='gluteRoundness'?'strongly rounded and highly dimensional yet anatomically coherent lower-body contours':phrases[f.key][band(f.value)]
export function buildNaturalBodyPrompt(state:BuilderStateV3){const main=mergeRelatedBodyFeatures(selectDominantBodyFeatures(state,1));return unique([buildHolisticBodyDescriptor(state),...main.map(f=>featurePhrase(f,state)),'harmonized body proportions with realistic anatomy'])}
export function buildImpactBodyPrompt(state:BuilderStateV3){const main=mergeRelatedBodyFeatures(selectDominantBodyFeatures(state,2));return unique([buildHolisticBodyDescriptor(state),...main.map(f=>featurePhrase(f,state)),'a clearly defined waist-to-hip transition with coherent anatomy'])}
export function getBodyPromptStrategy(state:BuilderStateV3){const top=mergeRelatedBodyFeatures(selectDominantBodyFeatures(state,2));const high=bodyKeys.filter(k=>state.body[k]>=81).length>=3||bodyKeys.filter(k=>state.body[k]>=61).length>=5;return{features:top.map(x=>labels[x.key]),groups:top.length,compressed:high,impact:state.body.visualImpact}}
export const buildPosePrompt=(s:BuilderStateV3)=>getPose(s.pose.poseId)?.prompt.en??'a coherent neutral pose';export const buildSupportStructurePrompt=(s:BuilderStateV3)=>unique([find(s.pose.handPosition),find(s.pose.legPosition)]).join(', ');export const buildSubjectViewPrompt=(s:BuilderStateV3)=>find(s.camera.subjectView)
const identity=(s:BuilderStateV3)=>['a completely fictional, clearly adult woman',find(s.persona.regionStyle),find(s.persona.ageBand),find(s.persona.archetype),...s.persona.vibes.map(find),find(s.face.faceShape),find(s.face.featureVibe),find(s.face.hairstyle),find(s.face.makeup),find(s.face.expression)]
const scene=(s:BuilderStateV3)=>[find(s.scene.location),find(s.scene.time),find(s.scene.atmosphere),find(s.lighting.lightType),find(s.lighting.rimLight),find(s.lighting.visualStyle)]
const shared=(s:BuilderStateV3,body:string[])=>[...identity(s),...body,find(s.outfit.type),find(s.outfit.color),find(s.outfit.style),find(s.outfit.fit),'fully and appropriately covered outfit',buildPosePrompt(s),buildSupportStructurePrompt(s),buildSubjectViewPrompt(s),find(s.pose.headDirection),find(s.camera.framing),find(s.camera.height),...scene(s)]
const safety=['mature adult presence','tasteful non-explicit photography','anatomically coherent proportions','realistic anatomy','original fictional identity','no resemblance to any real person']
export const dedupePromptDescriptors=(items:string[])=>unique(items);export const enforcePromptWordBudget=(items:string[],max=230)=>{const result:string[]=[];let count=0;for(const item of items){const words=item.split(/\s+/).length;if(count+words>max)break;result.push(item);count+=words}return result}
export const buildNaturalPrompt=(s:BuilderStateV3)=>enforcePromptWordBudget(dedupePromptDescriptors([...shared(s,buildNaturalBodyPrompt(s)),mapSliderToPromptFragment('visualImpact',s.body.visualImpact,'natural'),...safety])).join(', ')
export const buildHighImpactPrompt=(s:BuilderStateV3)=>enforcePromptWordBudget(dedupePromptDescriptors([...shared(s,buildImpactBodyPrompt(s)),mapSliderToPromptFragment('visualImpact',s.body.visualImpact,'impact'),...safety])).join(', ')
export function validatePromptBalance(prompt:string):ValidationResult{const count=(word:string)=>(prompt.match(new RegExp(`\\b${word}\\b`,'gi'))??[]).length;const messages:string[]=[];if(count('dramatic')>1)messages.push('dramatic 超過一次');if(/dramatic projection/i.test(prompt))messages.push('包含 dramatic projection');if(prompt.includes('undefined'))messages.push('包含 undefined');for(const required of['clearly adult','fictional','non-explicit','realistic anatomy','anatomically coherent'])if(!prompt.includes(required))messages.push(`缺少 ${required}`);return{isValid:!messages.length,messages}}
export const buildCharacterSummary=(s:BuilderStateV3)=>unique([findOption(s.persona.archetype)?.labelZh??'虛構成年女性',findOption(s.persona.ageBand)?.labelZh??'明確成年',getPose(s.pose.poseId)?.labelZh??'自訂姿態',findCompositionOption(s.camera.subjectView)?.labelZh??'',findCompositionOption(s.camera.framing)?.labelZh??'',`視覺衝擊 ${s.body.visualImpact}`]).join('\n')
export const buildNegativePrompt=()=>unique([...negativePromptTerms,'real person likeness','celebrity likeness','fetishized body-part close-up']).join(', ');export const buildAllPrompts=(s:BuilderStateV3)=>`角色摘要\n────\n${buildCharacterSummary(s)}\n\nNatural Portrait Prompt\n────\n${buildNaturalPrompt(s)}\n\nHigh-Impact Editorial Prompt\n────\n${buildHighImpactPrompt(s)}\n\nNegative Prompt\n────\n${buildNegativePrompt()}`
export const validateBuilderState=(s:BuilderStateV3):ValidationResult=>({isValid:s.schemaVersion===3&&s.dataVersion==='0.2.1'&&Object.values(s.systemLocks).every(Boolean),messages:[]});export const validateResolvedPrompt=(s:BuilderStateV3)=>{const structure=validateFinalPrompt(buildNaturalPrompt(s)),balance=validatePromptBalance(buildHighImpactPrompt(s));return{isValid:structure.isValid&&balance.isValid,messages:[...structure.messages,...balance.messages]}};export const applyCharacterPreset=(p:CharacterPreset)=>structuredClone(p.state)
